version: '3.8'

services:
  db:
    image: tobi312/rpi-postgresql-postgis:15-3.4-alpine-arm
    environment:
      POSTGRES_DB: road_rover
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - road_rover_data:/var/lib/postgresql/data

volumes:
  road_rover_data:
