version: '3.8'

services:
  db:
    image: kartoza/postgis:16-3.4--v2024.03.17
    environment:
      POSTGRES_DB: road_rover
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - road_rover_data:/var/lib/postgresql/data

volumes:
  road_rover_data:
