---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      #- SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
