---
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=road-rover
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped
