apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: 192.168.0.135
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      postgresVersion: 15
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    basicAuth: false
    basicAuthUser: root
